site_name: ErgoDocs
site_url: https://docs.ergoplatform.com
repo_url: https://github.com/glasgowm148/ergodocs
edit_uri: edit/main/docs/


theme:
    name: material
    favicon: assets/favicon.png
    palette: # dark scheme toggle on material + dark orange
      - scheme: slate
        primary: red
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - scheme: default
        primary: red
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    features:
        - navigation.tabs.sticky
        - navigation.instant
        - navigation.sections # The bold sections in navigation
        - navigation.tracking
        - navigation.indexes
      #  - toc.integrate
    logo: assets/logo.png
    font:
      text: Roboto
extra_css: 
  - assets/extra.css
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - assets/extra.js
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

extra:
  version:
    provider: mike


extra:
  generator: false


plugins:
  - search

markdown_extensions:
  - meta
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:
      generic: true



nav:
  - Getting Started:
    - Getting Started: index.md
    - Contributing: contribute.md
    - FAQ: faq.md
    - Events: 
      - Events: events/index.md
      - ERGOHACK: events/ergohack.md
      - ErgoSummit: events/ergosummit.md
    - Social Contract: social_contract.md
  - 🔬 ┃ Learn: 
    - Protocol: dev/protocol/index.md
    - eUTXO: dev/protocol/eutxo.md
    - NIPoPoWS: dev/protocol/nipopow.md
    - Scaling: dev/protocol/scaling.md
    - EIPs: dev/protocol/eip.md
    - Documents: documents.md
  - 🛠 ┃ Build:
    - Developers: dev/index.md
    - Data Model:
      - Transactions: dev/protocol/transaction.md
      - Box:
        - Box: dev/data-model/box/index.md
        - Registers: dev/data-model/box/registers.md
      - Block: dev/data-model/block.md
      #- UTXO-State: 
    - Wallets:
      - Wallets: dev/wallet/index.md
      - Addresses: dev/wallet/address.md
      - Hierarchical keys: dev/wallet/keys.md
      - Payments:
        - ErgoPay: dev/wallet/payments/ergo-pay.md
        - dApp Connector: dev/wallet/payments/dApp.md
        - Proxy Contracts: dev/wallet/payments/proxy.md
        - Ledger: dev/wallet/payments/ledger.md
    - Smart Contracts:
      - Smart Contracts: dev/scs/index.md
      - ErgoScript: 
        - Overview: dev/scs/ergoscript.md
        - Quick Primer: dev/scs/ergoscript-primer.md
        - Sigma Language: dev/scs/sigma-lang.md
      - Features: 
        - Sigma Protocols: dev/scs/sigma.md
        - Data Inputs: dev/scs/data-inputs.md
        - Multi-Stage Contracts: dev/scs/multi.md 
      - FlowCards: dev/scs/flowcards.md
      - ErgoTree: dev/scs/ergotree.md
    - P2P:
      - P2P: dev/p2p/index.md
      - Handshaking: dev/p2p/p2p-handshake.md
      - Network Messages: dev/p2p/network.md
     # - Modifiers Exchange: dev/p2p/modifiers.md
     # - BlockP2P: dev/p2p/BlockP2P.md
    - Resources: 
      - Libraries:
        - AppKit:
          - AppKit: dev/stack/appkit/index.md
          - Tutorial: dev/stack/appkit/tutorial.md
        - ErgoTool: dev/stack/ergotool.md
        - Kiosk: dev/stack/kiosk.md
        - JDE: dev/stack/jde.md
        - Assembler: dev/stack/assembler.md
        - HDF: dev/stack/headless.md
      - Languages:
        - Scala: dev/Languages/scala.md
        - Java: dev/Languages/java.md
        - Rust: dev/Languages/rust.md
        - Python: dev/Languages/python.md
        - C#: dev/Languages/csharp.md
      - Stack: 
        - Front-End: dev/stack/front-end.md
        - Back-End: dev/stack/back-end.md
      - Tutorials:
       #- Dust: node/dust.md
        - Pi Blockchain Explorer: dev/stack/rpi-blockchain-explorer.md
        - Integration: dev/Integration/guide.md
      - Misc: 
        - Bookmarks: dev/start/resources.md
        - Audit: dev/protocol/audit.md
        - EIP27: dev/protocol/eip27.md
  - ⛏ ┃  Mining:
    - Mining: mining/index.md
    - Dig in: 
      - Join a Pool: mining/setup/join.md
      - Solo Mining: mining/setup/solo.md
      - Host a Pool: mining/setup/pool.md
      - Subpooling: mining/setup/subpool.md
    - Autolykos: mining/autolykos.md
    - Governance: mining/governance.md
    - Storage Rent: mining/rent.md
    - Log-Space Mining: mining/log_space.md
  - 📦 ┃  Node:
    - Node: node/index.md
    - Install: 
      - Install: node/install/index.md
      #- Mac: node/install/mac.md
      #- Windows: node/install/windows.md
      #- Linux: node/install/linux.md
      - Troubleshooting: node/install/troubleshooting.md
      - Docker: node/install/docker.md
      - Pi: node/install/pi.md
    - Overview:
      - Wallet: node/wallet.md
      - Swagger API: node/swagger.md
      - FAQ: node/install/faq.md
      #- Architecture: node/architecture.md
      - Distributed Signatures: node/sigs.md
      - Modes of Operation: node/modes.md
      - Explorer: node/explorer.md
    - Test-net: dev/start/testnet.md
    #- Light Modes: 
    #  - Digest State: node/digest-state.md
    #  - History Pruning: node/history-pruning.md
    #  - Snapshots: node/snapshots.md
   #   - NiPoPoWS: dev/protocol/nipopow.md

  - 💡 ┃  Applications:
    - Applications: uses/index.md
    - Live dApps:
      - DEXs: uses/dex.md
      - Stablecoins: uses/stablecoins.md
      - Oracles: uses/oracles.md
      - NFTs: uses/nft.md
      - Mixing: uses/mixer.md
      - CrowdFunding: uses/crowdfunding.md
     #- ErgoRaffle: uses/raffle.md
    - In Development:
      - ProfitSharing: uses/profit.md
      - ICOs: uses/ico.md
      - Index Coins: uses/index_coins.md
      - Lending: uses/lending.md
      - Zero-Knowledge: uses/zk.md      
    - Planned:
      - Asset Tokenisation: uses/tokenisation.md
      - DAO: uses/dao.md
      - Buy Back Guarantees: uses/dex-buyback.md
      - LETS: uses/lets.md
      - Trustlss LETS: uses/trustless-lets.md
      - Email Client for Blocked Internet: uses/blocked_web.md
      - Atomic Swaps: dev/protocol/atomic.md
      - ErgoData: uses/ErgoData.md
    - Further Ideas:
      - CDBC: uses/cbdc.md
      - Lotteries: uses/lottery.md
      - Insurance: uses/insurance.md
      - Derivatives: uses/deriv.md
      - Yield Aggregation: uses/yield.md
      - Micro Credit: dev/scs/microcredit.md
      - Math Fun: uses/math_fun.md
      - PoW Tokens: uses/PoW_tokens.md
      - Collateral Mining: uses/collateral-mining.md
      - Mutual Credit: uses/mutual_credit.md
      - Prediction Markets: uses/prediction_markets.md
      - Privacy: uses/privacy.md
      - Perpetual Tokens: uses/perpetual.md
      - Bonding Curve: uses/bonding.md
      - Context Claims: uses/context-claims.md


      




